### PR TITLE
Fix calendar bug in AngularJS

### PR DESCRIPTION
**Pull request by NexonSU**
Seems like quotation marks not allowed in strings.
Also fix Special Player translate.

### CODE REVIEW

**Comment by Prophet731** [comment]
It should work just fine with quotes.

**Comment by NexonSU** [comment]
No, it's not.
gif

**Comment by Prophet731** [comment]
Try this, edit your language file and replace
`"Отмена"`
with
`\"Отмена\"`

see if that fixes the problem. I'll remove the quotes if that still doesn't fix it.

**Comment by NexonSU** [comment]
Yes, escaping fix this error. But, still, this is not the best practice

**Comment by Prophet731** [comment]
It's not bad practice. Usually php it's single quotes while Javascript is double quotes. I'll see though about having it escape when it echos out. For now though, just update the file with my cage and I'll merge it.

**Comment by NexonSU** [comment]
Done.

**Pull request merged**
